### ISSUE TITLE
关于vue3+ant开源共建

### ISSUE THREAD

**Issue by rennzhang** [StavinLi/Workflow-Vue3#6]
我正在使用这个项目，用于业务开发，并改为 ant Design Vue 组件库，如果您需要，我可以提供代码

只改变了 ui库，逻辑保持一致

或者您同意的话我将发布到自己的仓库，并标明来源

**Comment by rennzhang** [comment]
细节过多，已放弃

**Comment by asang28** [comment]
找到平替了吗，还是没做了
